### ISSUE TITLE
Segmentation fault when asking for value outside of range of interpolation table

### ISSUE THREAD

**Issue by david8dixon** [njoy/interpolation#2]
Disregard

**Comment by apmccartney** [comment]
This is operating as intended (which may seem strange). 

The table splits the number line into three intervals: defined, left and right.

```
<-------------------| i i i i i i i i i i i i i i i i |------------------>
    left                         defined                   right
```

In the defined interval, we have specified x- and y-values and have one or more interpolation schemes to determine values in between. How the left and right are handled is specified at compile time using facets/decorators (see example 6). In the absense of that specification, behavior is undefined in these regions (which might be desirable for validated input)
